name: build

on: 
  push:
    branches:
      - develop
      - release_7*
      - release_6.5
    tags:
      - v*
    
  pull_request:
    branches: 
    - develop
    - release_7*
    - release_6.5

jobs:
  build:
    name: Build
    runs-on: windows-2019
    # info about windows-2019 https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md
    env:
      DROP_DIR: drop
    steps:
      - uses: actions/checkout@v1
      - name: Build Everything
        shell: powershell
        run: ./build.ps1
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: release_drop
          path: ${{ env.DROP_DIR }}